### ISSUE TITLE
Mobile view issue ´

### ISSUE THREAD

**Issue by gustavcorpas** [gustavcorpas/spyfall#4]
The mobile view looks weird now for some reason.

**Comment by atjn** [comment]
Hmm. Seems like a wierd issue with the way the viewport is set up and interacts with the viewport meta tag added in 99adf36

I will remove the meta tag for now, but the root issue should really be fixed instead. Without the meta tag, the browser won't render text correctly, and will be guessing the viewport size, resulting in all sorts of wierd behaviour.
